export enum QUERY_KEYS {
  // AUTH KEYS
  GET_ALL_DAY_TRENDINGS = "getDayTrendings",
  GET_ALL_WEEK_TRENDINGS = "getWeekTrendings",
  GET_INFINIT_POPULARE_MOVIES = "getInfinitPopulareMovies",
  GET_RECOMENDED_MOVIES = "getRecomendedMovies",
  GET_MOVIE_BY_ID = "getMoviebyId",
  GET_MOVIE_RELEASE_BY_ID = "getMovieReleaseDatebyId",
  GET_MOVIE_DIRECTOR_WRITER = "getDirector&Writer",
  GET_MOVIE_CREDITS_BY_ID = "getMovieCreditsbyId",
  GET_MOVIE_Image_BY_ID = "getMovieImagesbyId",
  GET_MOVIE_VIDEO_BY_ID = "getMovieVideosbyId",
  GET_NOW_PLAYING_MOVIES = "getInfinityNowPlayingMovies",
  GET_TOP_RATED_MOVIES = "getTopRatedMovies",
  GET_UPCOMING_MOVIES = "getInfinityUpcomingMovies",
  GET_MOVIES_BY_GENRE = "getMoviesByGenre",
  GET_SERIES_BY_ID = "getSeriesbyId",
  GET_SERIES_CREDIT_BY_ID = "getSeriesCreditById",
  GET_SERIES_IMAGE_BY_ID = "getSeriesImageById",
  GET_SERIES_VIDEO_BY_ID = "getSeriesVideoById",
  GET_SERIES_RECOMENDED_BY_ID = "getSeriesRecomendedById",
  GET_TOP_RATED_SERIES = "getTopRatedSeries",
  GET_ON_AIR_SERIES = "getOnAirSeries",
  GET_AIRING_TODAY_SERIES = "getAiringTodaySeries",
  GET_POPULARE_SERIES = "getPoplareSries",
  GET_Series_Creator = "getSeriesCreator",
  GET_SERIES_BY_GENRE = "getSeriesByGenre",
  GET_CURRENT_USER='getCurrentUser'
}
